// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh0n5cC-GPGWEiAD0YqK02rxv7IfuuTeg',
    appId: '1:607656384066:web:0ce7f94004553cdd3c3fdb',
    messagingSenderId: '607656384066',
    projectId: 'newapp4-99ca9',
    authDomain: 'newapp4-99ca9.firebaseapp.com',
    storageBucket: 'newapp4-99ca9.firebasestorage.app',
    measurementId: 'G-34JN6XB5BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm1eEZZN8AgA2PsWK9yv9BDUwmxOWiVQY',
    appId: '1:607656384066:android:fa736b18534f39583c3fdb',
    messagingSenderId: '607656384066',
    projectId: 'newapp4-99ca9',
    storageBucket: 'newapp4-99ca9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzyfEwTjFlaPoYB-9CWfgSt_AmqTvUE0w',
    appId: '1:607656384066:ios:c8107d7720ed697e3c3fdb',
    messagingSenderId: '607656384066',
    projectId: 'newapp4-99ca9',
    storageBucket: 'newapp4-99ca9.firebasestorage.app',
    iosBundleId: 'com.example.newApp4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzyfEwTjFlaPoYB-9CWfgSt_AmqTvUE0w',
    appId: '1:607656384066:ios:c8107d7720ed697e3c3fdb',
    messagingSenderId: '607656384066',
    projectId: 'newapp4-99ca9',
    storageBucket: 'newapp4-99ca9.firebasestorage.app',
    iosBundleId: 'com.example.newApp4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh0n5cC-GPGWEiAD0YqK02rxv7IfuuTeg',
    appId: '1:607656384066:web:3b67f29ad90eaaba3c3fdb',
    messagingSenderId: '607656384066',
    projectId: 'newapp4-99ca9',
    authDomain: 'newapp4-99ca9.firebaseapp.com',
    storageBucket: 'newapp4-99ca9.firebasestorage.app',
    measurementId: 'G-C6MNHQMW7D',
  );
}
